library(ggplot2)
library(dplyr)

# Function to generate a model that simulates two agents' dyadic behaviors.
# @param C: context matrix C, a 2x2 matrix 
#           (how much Person A influences self, how much Person B influences Person A;
#           (how much Person A influences Person B, how much Person B influences self)
# @param iterations: number of behaviors to simulate for each C matrix
runModel = function(C,iterations) {
  
  # initialize behaviors for Person A and Person B
  beh_A = runif(1)-.5 
  beh_B = runif(1)-.5 
  beh = c(beh_A, beh_B)
  beh_history = c(beh_A,beh_B)
  
  for (i in 1:iterations) {

    # note: 0.5 = power of influence, currently set as equivalent between two agents 
    # i.e. Person A and Person B are equally influential in each other's behaviors
    beh = 0.5 * (C %*% beh) + (runif(2) - 0.5) - 0.1 * beh
    beh_history = rbind(beh_history,
                                data.frame(A = beh[1],B = beh[2]))
  }
  
  ts1 = beh_history$A 
  ts2 = beh_history$B 
  
  ccf_rs = ccf(ts1,ts2,20,plot=F)
  p1_offs = which(ts1 < (mean(ts1)-sd(ts1)))
  p2_ons = which(ts2 > (mean(ts2)+sd(ts2)))
  
  lags = c()
  for (i in 1:length(p1_offs)) {
    on_lag = p2_ons - p1_offs[i]
    ix = which.min(abs(on_lag))
    lags = c(lags, on_lag[ix])
  }
  h=hist(lags,10,plot=F)
  
  return(list(ts1,ts2,ccf_rs,h$mids,h$counts))
}

# Function to plot simulated behaviors generated by two agents 
# @param ts1: time series of Person A 
# @param ts2: time series of Person B 
# @main: title of the plot
# @col1: color of Person A's behavioral line 
# @col2: color of Person B's behavioral line 
plotResults = function(ts1,ts2,main,col1,col2) {
  lowEnd = -1.5
  plot(ts1,type='l',lwd=2,main=main,col=col1,
       ylim=c(lowEnd,abs(lowEnd)),xlab='Time (iteration)',ylab='Agent behavior')
  points(ts2,type='l',lwd=2,main=main,col=col2)
  text(0,lowEnd+.1,pos=4,paste('r = ',round(cor(ts1,ts2),2),sep=''),cex=2)
}

############################################################
############################################################
############################################################
############################################################
############################################################
############################################################
############################################################
############################################################
#
# NEW! for functions:
#
#

plotCcf = function(res, col='pink', p_add=NULL) {
  
  ribs = c()
  print('preparing long-form results')
  for (i in 1:nrow(res)) {
    tmp = res[i,]
    vs = as.numeric(tmp[9:49])
    ribs = rbind(ribs, data.frame(lag=(-20:20), r=vs, row.names = NULL))
  }
  
  ribs_summary <- ribs %>%
    group_by(lag) %>%
    summarise(mean_r=mean(r), sd_r=sd(r))
  
  if (is.null(p_add)) {
    p = ggplot() + theme_minimal() + labs(title="Ribbon Plot", x="Lag", y="Mean r")
  } else {
    p = p_add
  }
  
  p = p+geom_ribbon(data=ribs_summary, aes(x=lag, ymin=mean_r-sd_r, ymax=mean_r+sd_r), fill=col, alpha=0.2)
  p = p+geom_line(data=ribs_summary, aes(x=lag, y=mean_r), color=col, size=1)
  
  return(p)
}



plotStivers = function(res, col='pink', p_add=NULL) {
  
  stivs = res
  
  stivs_summary <- stivs %>%
    group_by(midBin) %>%
    summarise(mean_c=mean(normalizedCounts), sd_c=sd(normalizedCounts)/sqrt(nrow(res)))
  
  stivs_summary = stivs_summary[!is.na(stivs_summary$sd_c),]
  
  if (is.null(p_add)) {
    p = ggplot() + theme_minimal() + labs(title="", x="Turn lag", y="Mean count")
  } else {
    p = p_add
  }
  
  p = p+geom_ribbon(data=stivs_summary, aes(x=midBin, ymin=mean_c-sd_c, ymax=mean_c+sd_c), fill=col, alpha=0.2)
  p = p+geom_line(data=stivs_summary, aes(x=midBin, y=mean_c), color=col, size=1)
  
  return(p)
}

