# Function to generate a model that simulates two agents' dyadic behaviors.
# @param C: context matrix C, a 2x2 matrix 
#           (how much Person A influences self, how much Person B influences Person A;
#           (how much Person A influences Person B, how much Person B influences self)
# @param iterations: number of behaviors to simulate for each C matrix
runModel = function(C,iterations) {
  
  # initialize behaviors for Person A and Person B
  beh_A = runif(1)-.5 
  beh_B = runif(1)-.5 
  beh = c(beh_A, beh_B)
  beh_history = c(beh_A,beh_B)
  
  for (i in 1:iterations) {

    # note: 0.5 = power of influence, currently set as equivalent between two agents 
    # i.e. Person A and Person B are equally influential in each other's behaviors
    beh = 0.5 * (C %*% beh) + (runif(2) - 0.5) - 0.1 * beh
    beh_history = rbind(beh_history,
                                data.frame(A = beh[1],B = beh[2]))
  }
  
  ts1 = beh_history$A 
  ts2 = beh_history$B 
  return(list(ts1,ts2))
}


# Function to plot simulated behaviors generated by two agents 
# @param ts1: time series of Person A 
# @param ts2: time series of Person B 
# @main: title of the plot
# @col1: color of Person A's behavioral line 
# @col2: color of Person B's behavioral line 
plotResults = function(ts1,ts2,main,col1,col2) {
  lowEnd = -1.5
  plot(ts1,type='l',lwd=2,main=main,col=col1,
       ylim=c(lowEnd,abs(lowEnd)),xlab='Time (iteration)',ylab='Agent behavior')
  points(ts2,type='l',lwd=2,main=main,col=col2)
  text(0,lowEnd+.1,pos=4,paste('r = ',round(cor(ts1,ts2),2),sep=''),cex=2)
}
